name: Dependabot Rebase

on:
  schedule:
    # Run every 6 hours to check for conflicts
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Rebase Dependabot PRs
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pullRequests } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              head: 'dependabot'
            });

            for (const pr of pullRequests) {
              if (pr.user.login === 'dependabot[bot]') {
                try {
                  // Check if PR has conflicts
                  const { data: prData } = await github.rest.pulls.get({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    pull_number: pr.number
                  });

                  if (prData.mergeable_state === 'dirty') {
                    console.log(`Rebasing PR #${pr.number}: ${pr.title}`);
                    
                    // Comment on the PR to trigger Dependabot rebase
                    await github.rest.issues.createComment({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      issue_number: pr.number,
                      body: '@dependabot rebase'
                    });
                  }
                } catch (error) {
                  console.log(`Error processing PR #${pr.number}: ${error.message}`);
                }
              }
            }
